# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'aserowy/tmux.nvim'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'
set -g @plugin 'robhurring/tmux-spotify'
set -g status-right "#{track} : #{artist}"

set -g mouse on
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip"
set-option -g history-limit 10000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
bind c new-window -c "#{pane_current_path}"
set -g status-style fg=black,bg=red
set -s escape-time 0

set-option -g default-shell /usr/bin/zsh

# Set prefix to Ctrl-Space instead of Ctrl-b
unbind C-b
set -g prefix C-space
bind q send-prefix

set -g status-keys vi
setw -g mode-keys vi

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Toggle zoom for current pane
bind -n C-z resize-pane -Z

# Add keybinds to switch between windows AND toggle zoom for swapped to pane with less input
bind -n M-h select-pane -L\; resize-pane -Z
bind -n M-j select-pane -D\; resize-pane -Z
bind -n M-k select-pane -U\; resize-pane -Z
bind -n M-l select-pane -R\; resize-pane -Z

# Change colors of borders in tmux
set -g pane-border-style fg=red
set -g pane-active-border-style "bg=default fg=red"

# Ensure home/end keys work
bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"

# Ensure truecolor
set -g default-terminal "$TERM"
set -ag terminal-overrides ",$TERM:Tc"

# navigation: tmux.nvim
set -g @tmux-nvim-navigation true
set -g @tmux-nvim-navigation-cycle true
set -g @tmux-nvim-navigation-keybinding-left 'C-h'
set -g @tmux-nvim-navigation-keybinding-down 'C-j'
set -g @tmux-nvim-navigation-keybinding-up 'C-k'
set -g @tmux-nvim-navigation-keybinding-right 'C-l'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
run-shell ~/clone/path/resurrect.tmux
