theme = "merionette"

[editor.statusline]
left = ["mode", "spinner", "file-modification-indicator"]
center = ["file-name"]
right = ["diagnostics", "position"]
separator = "│"
mode.normal = "normal"
mode.insert = "insert"
mode.select = "select"


[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.gutters.line-numbers]
min-width = 1

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.lsp]
display-messages = true
